"""add_test_case_table

Revision ID: 5f03b52ee610
Revises: 73283fd4a584
Create Date: 2026-02-11 18:08:05.583898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f03b52ee610'
down_revision: Union[str, Sequence[str], None] = '73283fd4a584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('body', sa.JSON(), nullable=True),
    sa.Column('body_type', sa.String(length=32), nullable=False),
    sa.Column('assertions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['api.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_case_api_id'), 'test_case', ['api_id'], unique=False)
    op.create_index(op.f('ix_test_case_id'), 'test_case', ['id'], unique=False)
    op.create_index(op.f('ix_test_case_name'), 'test_case', ['name'], unique=False)
    op.create_index(op.f('ix_test_case_project_id'), 'test_case', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_case_project_id'), table_name='test_case')
    op.drop_index(op.f('ix_test_case_name'), table_name='test_case')
    op.drop_index(op.f('ix_test_case_id'), table_name='test_case')
    op.drop_index(op.f('ix_test_case_api_id'), table_name='test_case')
    op.drop_table('test_case')
    # ### end Alembic commands ###
