"""add_api_tables_retry

Revision ID: 73283fd4a584
Revises: fc7c314165d1
Create Date: 2026-02-11 17:15:57.665365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73283fd4a584'
down_revision: Union[str, Sequence[str], None] = 'fc7c314165d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('url_path', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_id'), 'api', ['id'], unique=False)
    op.create_index(op.f('ix_api_module_name'), 'api', ['module_name'], unique=False)
    op.create_index(op.f('ix_api_name'), 'api', ['name'], unique=False)
    op.create_index(op.f('ix_api_project_id'), 'api', ['project_id'], unique=False)
    op.create_table('api_request_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('path_params', sa.JSON(), nullable=True),
    sa.Column('query_params', sa.JSON(), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('body', sa.JSON(), nullable=True),
    sa.Column('body_type', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['api.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_id')
    )
    op.create_index(op.f('ix_api_request_template_id'), 'api_request_template', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_request_template_id'), table_name='api_request_template')
    op.drop_table('api_request_template')
    op.drop_index(op.f('ix_api_project_id'), table_name='api')
    op.drop_index(op.f('ix_api_name'), table_name='api')
    op.drop_index(op.f('ix_api_module_name'), table_name='api')
    op.drop_index(op.f('ix_api_id'), table_name='api')
    op.drop_table('api')
    # ### end Alembic commands ###
